language: node_js
dist: trusty
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
node_js:
  - 8
cache:
  directories:
    - node_modules
before_install:
  - pip3 install --upgrade --user awscli
script:
    - cd webapp
    - npm install
    - npm run build
    - npm test
deploy:
  - provider: script
    script: aws s3 sync webapp/build/ s3://$AWS_BUCKET_NAME --delete
    skip_cleanup: true
    on:
      branch: master
